ifndef::env-github[:icons: font]
ifdef::env-github[]
:status:
:outfilesuffix: .adoc
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :page_with_curl:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]

= Code Appendix for "BPjs - A Behavioral Programming Tool Suite"

_This is a code appendix for a paper submitted to Science of Computer Programming._

== Content

link:hello-world[]::
    The hello-world program presented at section 4.1.

link:GUI MazeRunner[]::
    GUI application for editing, running, and analyzing maze simulations. It also demonstrates how to use BPjs to embed a b-program in a traditional application. Presented at section 4.2.

link:StateSpaceMapper[]::
    A utility built on top of BPjs. Analyzes b-programs and creates a state-space graph diagram, in the link:http://graphviz.org[dot] language.

link:PerformanceTester[]::
    Code for an experiment measuring the performance of BPjs as a verification engine for b-programs.

link:BPJ+JPF[]::
    Code for an experiment measuring the performance of BPJ and NASA's JavaPathFinder as a verification engine for b-programs.

link:README.adoc[]::
    `this` file.
